version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
     - ${WP_DEV_PORT}:80
    restart: always
    env_file:
      - .env
volumes:
  db_data: